name: CD Build
description: Builds a release and pushes it to nuget

inputs:
  version:
    description: Release Version
    required: true
  nugetKey:
    description: Nuget key
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.0.x
          8.0.x
    - name: Release Build
      shell: bash
      run: |
        dotnet pack \
          --configuration Release \
          -p:ContinuousIntegrationBuild=true \
          -p:PackageVersion=${{ inputs.version }}
          
    - name: Push to Nuget
      shell: bash
      run: |
        dotnet nuget push **\*.nupkg \
          --api-key ${{ inputs.version }}
          --source https://api.nuget.org/v3/index.json --skip-duplicate
