name: Check C# Formatting
description: Runs the csharpier check over the code base

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install dotnet Tooling
      shell: bash
      run: dotnet tool restore
    - name: Check format
      shell: bash
      run: dotnet csharpier . --check